export const imageArray = [
  { id: 0, src: require("../assets/2x/Artboard 2@2x.png") },
  { id: 1, src: require("../assets/2x/Artboard 3@2x.png") },
  { id: 2, src: require("../assets/2x/Artboard 4@2x.png") },
  { id: 3, src: require("../assets/2x/Artboard 5@2x.png") },
  { id: 4, src: require("../assets/2x/Artboard 6@2x.png") },
  { id: 5, src: require("../assets/2x/Artboard 7@2x.png") },
  { id: 6, src: require("../assets/2x/Artboard 8@2x.png") },
  { id: 7, src: require("../assets/2x/Artboard 9@2x.png") },
  { id: 8, src: require("../assets/2x/Artboard 10@2x.png") },
  { id: 9, src: require("../assets/2x/Artboard 11@2x.png") },
  { id: 10, src: require("../assets/2x/Artboard 12@2x.png") },
  { id: 11, src: require("../assets/2x/Artboard 13@2x.png") },
  { id: 12, src: require("../assets/2x/Artboard 14@2x.png") },
  { id: 13, src: require("../assets/2x/Artboard 15@2x.png") },
  { id: 14, src: require("../assets/2x/Artboard 16@2x.png") },
  { id: 15, src: require("../assets/2x/Artboard 17@2x.png") },
  { id: 16, src: require("../assets/2x/Artboard 18@2x.png") },
  { id: 17, src: require("../assets/2x/Artboard 19@2x.png") },
];
